[package]
name = "escrow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.18.0"
tokio = "*"
clap = { version = "4.0.32", features = ["derive"] }
clap-num = "1.0.2"
hex-literal = "0.3.4"